baseURL = 'https://googlecloudplatform.github.io/samples-style-guide/'
title = 'Samples Style Guide | Google Cloud'
theme = ["docsy"]
languageCode = 'en-us'
enableGitInfo = true

[Params]
  copyright = 'Google LLC'
  github_repo = "https://github.com/GoogleCloudPlatform/samples-style-guide"

[[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/GoogleCloudPlatform/samples-style-guide"
    pre = "<i class='fab fa-github'></i>"

[module]
[[module.mounts]]
  source = 'content/en'
  target = 'content'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      guessSyntax = "true"
